#!/usr/bin/perl

use strict;
use Cwd;
use GSBL::Client ':all';

use FindBin qw($RealBin);
use lib "$RealBin/../lib";

my %option_desc = ( 


	arg0 => { 	TYPE => "s",
		 OPTIONAL_FLAG => "0",
		 OPTIONAL_VALUE => "0",
		 KEY => "paramFile",
		 TAKES => qq{file},
		 DESC => qq{The parameter file for the application.},
	},


);

my $properties = process_options(\%option_desc, "Migrate");

my $pid = $$;
my $jobname = "not initialized";

if($properties =~ /jobname \@-- (.*) \@-- java.lang.String/) { # override job name
    $jobname = $1;
    my @properties_chunks = split(/\n/, $properties);
    my $new_properties = "";
    foreach my $chunk(@properties_chunks) {
	if(!($chunk =~ /jobname.*java.lang.String/)) {
	    $new_properties .= $chunk . "\n";
	}
    }
    $properties = $new_properties;
} else {
    my $wd = getcwd;
    $wd =~ /.*\/(.*)/;
    $wd = $1;
    $jobname = $wd;
}

open(PROPERTIES_OUT, ">Migrate.properties.$pid") || die "Cannot write properties file: $!";
print PROPERTIES_OUT $properties;
close(PROPERTIES_OUT);

system("java -DGLOBUS_LOCATION=\$GLOBUS_LOCATION -classpath $RealBin:$RealBin/build/classes/:$RealBin/build/stubs/classes/:\$CLASSPATH edu.umd.grid.bio.migrate.clients.MigrateSubmitClient https://leucine.umiacs.umd.edu:8443/wsrf/services/edu/umd/grid/bio/migrate/MigrateFactoryService Migrate.properties.$pid $jobname");

unlink("Migrate.properties.$$");

