#!/usr/bin/perl
use strict;
use warnings;

# Large number of reps in the associated mainparams file
#
# To run this test script, you must first copy main_params_long to mainparams 
# and extraparams in the main structure directory.  Then move testdata1 and
# this file to the main structure directory as well.
#
#
# Output files: structure_test_long.out_f
#
# Approx runtime: 5 min

my $output = `./Structure_submit -i testdata1 -o structure_test_long.out`;
print "stdout:\n";
print $output;
