suppressPackageStartupMessages(library(randomForest))
load("garli_recent.rf")
garli_estimate_one <- read.table("85693250.5931571764761226_estimate",header=T)
garli.pred <- predict(garli_recent.rf, garli_estimate_one[1,])
cat('ESTIMATE: ',as.integer(garli.pred[1]),'\n',sep="")
