#!/usr/bin/perl

use strict;
use Cwd;
use GSBL::Client ':all';

use FindBin qw($RealBin);
use lib "$RealBin/../lib";

my %option_desc = ( 


	arg1 => { 	TYPE => "s",
		 OPTIONAL_FLAG => "0",
		 OPTIONAL_VALUE => "0",
		 KEY => "paramFile",
		 TAKES => qq{param_file},
		 DESC => qq{File containing the parameters needed by lam_conv and lamarc},
	},

	o => { 	TYPE => "s",
		 OPTIONAL_FLAG => "1",
		 OPTIONAL_VALUE => "0",
		 KEY => "outputFile",
		 TAKES => qq{output_file},
		 DESC => qq{Output file to hold main results of lamarc computation},
	},

	arg0 => { 	TYPE => "s",
		 OPTIONAL_FLAG => "0",
		 OPTIONAL_VALUE => "0",
		 KEY => "dataFile",
		 TAKES => qq{data_file},
		 DESC => qq{File containing the data that lamarc is to process. Acceptable data files are PHYLIP, COALESCE/FLUCTUATE, and MIGRATE/RECOMBINE files},
	},


);

my $properties = process_options(\%option_desc, "LAMARC");

my $pid = $$;
my $jobname = "not initialized";

if($properties =~ /jobname \@-- (.*) \@-- java.lang.String/) { # override job name
    $jobname = $1;
    my @properties_chunks = split(/\n/, $properties);
    my $new_properties = "";
    foreach my $chunk(@properties_chunks) {
	if(!($chunk =~ /jobname.*java.lang.String/)) {
	    $new_properties .= $chunk . "\n";
	}
    }
    $properties = $new_properties;
} else {
    my $wd = getcwd;
    $wd =~ /.*\/(.*)/;
    $wd = $1;
    $jobname = $wd;
}

open(PROPERTIES_OUT, ">LAMARC.properties.$pid") || die "Cannot write properties file: $!";
print PROPERTIES_OUT $properties;
close(PROPERTIES_OUT);

system("java -DGLOBUS_LOCATION=\$GLOBUS_LOCATION -classpath $RealBin:$RealBin/build/classes/:$RealBin/build/stubs/classes/:\$CLASSPATH edu.umd.grid.bio.lamarc.clients.LAMARCSubmitClient https://lysine.umiacs.umd.edu:8443/wsrf/services/edu/umd/grid/bio/lamarc/LAMARCFactoryService LAMARC.properties.$pid $jobname");

unlink("LAMARC.properties.$$");

