<?xml version="1.0" encoding="UTF-8"?>
<definitions name="MARXANFactoryService"
    targetNamespace="http://www.umd.edu/namespaces/grid/bio/MARXANFactoryService"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="http://www.umd.edu/namespaces/grid/bio/MARXANFactoryService"
    xmlns:wsa="http://www.w3.org/2005/08/addressing"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdlpp="http://www.globus.org/namespaces/2004/10/WSDLPreprocessor"
    xmlns:gsbl="http://cummings.umiacs.umd.edu/GSBL/GT42GSBLFactoryService.wsdl"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:import namespace="http://cummings.umiacs.umd.edu/GSBL/GT42GSBLFactoryService.wsdl"
        location="/fs/mikeproj/grid/www/cummings/GSBL/GT42GSBLFactoryService.wsdl"/>
    <types>
        <xsd:schema targetNamespace="http://www.umd.edu/namespaces/grid/bio/MARXANFactoryService"
            xmlns:tns="http://www.umd.edu/namespaces/grid/bio/MARXANFactoryService"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.w3.org/2005/08/addressing"
                schemaLocation="/fs/mikeproj/grid/www/cummings/ws/addressing/ws-addr.xsd"/>
        </xsd:schema>
    </types>
    <portType name="MARXANFactoryPortType" wsdlpp:extends="gsbl:GT42GSBLFactoryServicePortType"/>
</definitions>
