#!/usr/bin/perl
use strict;
use warnings;

# Medium number of reps in the associated mainparams file
# Testing the -N option as well
#
# To run this test script, you must first copy main_params_medium to mainparams 
# and extraparams in the main structure directory.  Then move testdata1 and
# this file to the main structure directory as well.
#
#
# Output files: structure_test_medium.out_f
#
# Approx runtime: 1 min

my $output = `./Structure_submit -i testdata1 -o structure_test_medium.out -N 200`;
print "stdout:\n";
print $output;
