<?xml version="1.0" encoding="UTF-8"?>
<definitions name="GsiFactoryService"
    targetNamespace="http://www.umd.edu/namespaces/grid/bio/GsiFactoryService"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="http://www.umd.edu/namespaces/grid/bio/GsiFactoryService"
    xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/03/addressing"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdlpp="http://www.globus.org/namespaces/2004/10/WSDLPreprocessor"
    xmlns:gsbl="http://cummings.umiacs.umd.edu/GSBL/GT4GSBLFactoryService.wsdl"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:import namespace="http://cummings.umiacs.umd.edu/GSBL/GT4GSBLFactoryService.wsdl"
        location="/fs/mikeproj/grid/www/cummings/GSBL/GT4GSBLFactoryService.wsdl"/>
    <types>
        <xsd:schema targetNamespace="http://www.umd.edu/namespaces/grid/bio/GsiFactoryService"
            xmlns:tns="http://www.umd.edu/namespaces/grid/bio/GsiFactoryService"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://schemas.xmlsoap.org/ws/2004/03/addressing"
                schemaLocation="/fs/mikeproj/grid/www/cummings/ws/addressing/WS-Addressing.xsd"/>
        </xsd:schema>
    </types>
    <portType name="GsiFactoryPortType" wsdlpp:extends="gsbl:GT4GSBLFactoryServicePortType"/>
</definitions>
