#!/usr/bin/perl
use strict;
use warnings;

#Short analysis
#
#To run this test script, you must first copy template2.nex, gene_seqs.nxs, 
#  and this file into the main ssearch34 directory
#
#Output files: paup_test_short_tree.phy, paup_test_short.log
#
#Approx time: < 1 min

my $output = `./PAUP_submit template2.nex`;
print "stdout:\n";
print $output;
